<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Parametric and non-parametric stability statistics • metan</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.3.7/spacelab/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha256-U5ZEeKfGNOja007MMD3YBI0A3OSZOQbeG6z2f2Y0hu8=" crossorigin="anonymous"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css" integrity="sha256-eZrrJcwDc/3uDhsdt61sL2oOBY362qM3lon1gyExkL0=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.4/clipboard.min.js" integrity="sha256-FiZwavyI2V6+EXO1U+xzLG3IKldpiTFf3153ea9zikQ=" crossorigin="anonymous"></script><!-- sticky kit --><script src="https://cdnjs.cloudflare.com/ajax/libs/sticky-kit/1.1.3/sticky-kit.min.js" integrity="sha256-c4Rlo1ZozqTPE2RLuvbusY3+SU1pQaJC0TjuhygMipw=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../pkgdown.css" rel="stylesheet">
<script src="../pkgdown.js"></script><meta property="og:title" content="Parametric and non-parametric stability statistics">
<meta property="og:description" content="">
<meta property="og:image" content="/logo.png">
<meta name="twitter:card" content="summary">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
    <div class="container template-article">
      <header><div class="navbar navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../index.html">metan</a>
        <span class="version label label-default" data-toggle="tooltip" data-placement="bottom" title="Released version">1.1.0</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../index.html">
    <span class="fa fa-home"></span>
     
    Home
  </a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    Examples
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../articles/vignettes_cross-validation.html">Cross-validation procedure</a>
    </li>
    <li>
      <a href="../articles/vignettes_ammi.html">AMMI</a>
    </li>
    <li>
      <a href="../articles/vignettes_blup.html">BLUP</a>
    </li>
    <li>
      <a href="../articles/vignettes_stability.html">Stability</a>
    </li>
    <li>
      <a href="../articles/vignettes_indexes.html">Multivariate indexes</a>
    </li>
    <li>
      <a href="../articles/vignettes_biometry.html">Biometry</a>
    </li>
    <li>
      <a href="../articles/vignettes_helper.html">Helper</a>
    </li>
  </ul>
</li>
<li>
  <a href="../reference/index.html">Functions</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
    More
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
<li>
      <a href="../CODE_OF_CONDUCT.html">Code of Conduct</a>
    </li>
    <li>
      <a href="../news/index.html">News</a>
    </li>
    <li>
      <a href="../LICENSE.html">Licence</a>
    </li>
  </ul>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://www.researchgate.net/profile/Tiago_Olivoto2">ResearchGate</a>
</li>
<li>
  <a href="https://www.mendeley.com/profiles/tiago-olivoto/">Mendeley</a>
</li>
<li>
  <a href="https://github.com/TiagoOlivoto">Github</a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      
      </header><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1>Parametric and non-parametric stability statistics</h1>
            
      
      <small class="dont-index">Source: <a href="https://github.com/TiagoOlivoto/metan/blob/master/vignettes/vignettes_stability.Rmd"><code>vignettes/vignettes_stability.Rmd</code></a></small>
      <div class="hidden name"><code>vignettes_stability.Rmd</code></div>

    </div>

    
    
<div id="getting-started" class="section level1">
<h1 class="hasAnchor">
<a href="#getting-started" class="anchor"></a>Getting started</h1>
<p>In this section, we will use the data in <code>data_ge2</code>. For more information, please, see <code><a href="../reference/data_ge2.html">?data_ge2</a></code>. Other data sets can be used provided that the following columns are in the dataset: environment, genotype, block/replicate and response variable(s).</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb1-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(metan)</a>
<a class="sourceLine" id="cb1-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(cowplot) <span class="co"># used to arrange the graphics</span></a>
<a class="sourceLine" id="cb1-3" title="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/library">library</a></span>(kableExtra) <span class="co"># Used to make the tables</span></a>
<a class="sourceLine" id="cb1-4" title="4">dataset =<span class="st"> </span>data_ge2</a>
<a class="sourceLine" id="cb1-5" title="5"><span class="kw"><a href="https://www.rdocumentation.org/packages/utils/topics/str">str</a></span>(dataset)</a></code></pre></div>
<pre><code>## 'data.frame':    156 obs. of  18 variables:
##  $ ENV : Factor w/ 4 levels "A1","A2","A3",..: 1 1 1 1 1 1 1 1 1 1 ...
##  $ GEN : Factor w/ 13 levels "H1","H10","H11",..: 1 1 1 2 2 2 3 3 3 4 ...
##  $ REP : Factor w/ 3 levels "1","2","3": 1 2 3 1 2 3 1 2 3 1 ...
##  $ PH  : num  2.61 2.87 2.68 2.83 2.79 ...
##  $ EH  : num  1.71 1.76 1.58 1.64 1.71 ...
##  $ EP  : num  0.658 0.628 0.591 0.581 0.616 ...
##  $ EL  : num  16.1 14.2 16 16.7 14.9 ...
##  $ ED  : num  52.2 50.3 50.7 54.1 52.7 ...
##  $ CL  : num  28.1 27.6 28.4 31.7 32 ...
##  $ CD  : num  16.3 14.5 16.4 17.4 15.5 ...
##  $ CW  : num  25.1 21.4 24 26.2 20.7 ...
##  $ KW  : num  217 184 208 194 176 ...
##  $ NR  : num  15.6 16 17.2 15.6 17.6 16.8 16.8 13.6 15.2 14.8 ...
##  $ NKR : num  36.6 31.4 31.8 32.8 28 32.8 34.6 34.4 34.8 31.6 ...
##  $ CDED: num  0.538 0.551 0.561 0.586 0.607 ...
##  $ PERK: num  89.6 89.5 89.7 87.9 89.7 ...
##  $ TKW : num  418 361 367 374 347 ...
##  $ NKE : num  521 494 565 519 502 ...</code></pre>
</div>
<div id="graphic-visualization-of-the-interaction" class="section level1">
<h1 class="hasAnchor">
<a href="#graphic-visualization-of-the-interaction" class="anchor"></a>Graphic visualization of the interaction</h1>
<p>The function <code><a href="../reference/ge_plot.html">ge_plot()</a></code> may be used to visualize the genotype’s performance across the environments. The black diamond shows the mean of each environment.</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb3-1" title="1">p1 =<span class="st"> </span><span class="kw"><a href="../reference/ge_plot.html">ge_plot</a></span>(dataset, ENV, GEN, KW)</a>
<a class="sourceLine" id="cb3-2" title="2">p2 =<span class="st"> </span><span class="kw"><a href="../reference/ge_plot.html">ge_plot</a></span>(dataset, ENV, GEN, KW) <span class="op">+</span><span class="st"> </span><span class="kw">theme_grey</span>() <span class="op">+</span><span class="st"> </span><span class="kw">coord_flip</span>()</a>
<a class="sourceLine" id="cb3-3" title="3"><span class="kw">plot_grid</span>(p1, p2)</a></code></pre></div>
<p><img src="vignettes_stability_files/figure-html/unnamed-chunk-2-1.png" width="960"></p>
</div>
<div id="joint-regression-analysis" class="section level1">
<h1 class="hasAnchor">
<a href="#joint-regression-analysis" class="anchor"></a>Joint regression analysis</h1>
<p><span class="citation">Eberhart and Russell (<a href="#ref-Eberhart1966">1966</a>)</span> popularized the regression-based stability analysis. In these procedures, the adaptability and stability analysis is performed by means of adjustments of regression equations where the dependent variable is predicted as a function of an environmental index, according to the following model:</p>
<p><span class="math display">\[
\mathop Y\nolimits_{ij}  = {\beta _{0i}} + {\beta _{1i}}{I_j} + {\delta _{ij}} + {\bar \varepsilon _{ij}}
\]</span> where <span class="math inline">\({\beta _{0i}}\)</span> is the grand mean of the genotype <em>i</em> (<em>i</em> = 1, 2, …, I); <span class="math inline">\({\beta _{1i}}\)</span> is the linear response (slope) of the genotype <em>i</em> to the environmental index; <em>Ij</em> is the environmental index (<em>j</em> = 1, 2, …, <em>e</em>), where <span class="math inline">\({I_j} = [(y_{.j}/g)- (y_{..}/ge)]\)</span>, <span class="math inline">\({\delta _{ij}}\)</span> is the deviation from the regression, and <span class="math inline">\({\bar \varepsilon _{ij}}\)</span> is the experimental error. The model is fitted with the function <code><a href="../reference/ge_reg.html">ge_reg()</a></code>. The S3 methods <code><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot()</a></code> and <code><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary()</a></code> may be used to explore the fitted model.</p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb4-1" title="1">reg_model =<span class="st"> </span><span class="kw"><a href="../reference/ge_reg.html">ge_reg</a></span>(dataset, ENV, GEN, REP, KW)</a>
<a class="sourceLine" id="cb4-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(reg_model<span class="op">$</span>KW)</a></code></pre></div>
<p><img src="vignettes_stability_files/figure-html/unnamed-chunk-3-1.png" width="480"></p>
<div class="sourceCode" id="cb5"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb5-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(reg_model)</a></code></pre></div>
<pre><code>## Variable KW 
## ---------------------------------------------------------------------------
## Joint-regression Analysis of variance
## ---------------------------------------------------------------------------
##                      Df Sum Sq Mean Sq F value   Pr(&gt;F)
## Total                51 127781  2505.5      NA       NA
## GEN                  12  21350  1779.2   1.061 4.29e-01
## ENV + (GEN x ENV)    39 106431  2729.0      NA       NA
## ENV (linear)          1  55465 55465.4      NA       NA
##  GEN x ENV (linear)  12   7370   614.2   0.366 9.64e-01
## Pooled deviation     26  43595  1676.7      NA       NA
## H1                    2    311   155.4   0.435 6.48e-01
## H10                   2    883   441.6   1.237 2.95e-01
## H11                   2    139    69.4   0.194 8.24e-01
## H12                   2   2171  1085.3   3.040 5.21e-02
## H13                   2   5789  2894.4   8.106 5.35e-04
## H2                    2   5740  2870.1   8.038 5.67e-04
## H3                    2   3808  1904.1   5.333 6.24e-03
## H4                    2   1913   956.7   2.680 7.33e-02
## H5                    2    575   287.5   0.805 4.50e-01
## H6                    2   5889  2944.3   8.246 4.74e-04
## H7                    2   4522  2261.0   6.333 2.54e-03
## H8                    2   7462  3730.9  10.449 7.33e-05
## H9                    2   4393  2196.7   6.152 2.98e-03
## Pooled error        104  37134   357.1      NA       NA
## ---------------------------------------------------------------------------
## Regression parameters
## ---------------------------------------------------------------------------
##  GEN Mean   bij   sdij  RMSE    R2
##   H1  184 0.844  -77.1  5.09 0.907
##  H10  164 1.395   18.3  8.58 0.904
##  H11  167 0.917 -105.8  3.40 0.963
##  H12  157 0.715  232.8 13.45 0.501
##  H13  180 0.637  835.9 21.96 0.230
##   H2  187 0.639  827.8 21.87 0.233
##   H3  169 0.970  505.8 17.81 0.513
##   H4  184 1.064  190.0 12.63 0.716
##   H5  184 0.606  -33.1  6.92 0.731
##   H6  188 1.609  852.5 22.15 0.652
##   H7  171 0.658  624.7 19.41 0.290
##   H8  160 1.247 1114.7 24.94 0.471
##   H9  153 1.699  603.3 19.13 0.737
## ---------------------------------------------------------------------------</code></pre>
</div>
<div id="genotypic-confidence-index" class="section level1">
<h1 class="hasAnchor">
<a href="#genotypic-confidence-index" class="anchor"></a>Genotypic confidence index</h1>
<p><span class="citation">Annicchiarico (<a href="#ref-Annicchiarico1992">1992</a>)</span> proposed that a stability method in which the stability parameter is measured by the superiority of the genotype in relation to the average of each environment, according to the following model:</p>
<p><span class="math display">\[
{Z_{ij}} = \frac{{{Y_{ij}}}}{{{{\bar Y}_{.j}}}} \times 100
\]</span> The genotypic confidence index of the genotype <em>i</em> (<span class="math inline">\(W_i\)</span>) is then estimated as follows:</p>
<p><span class="math display">\[
W_i = Z_{i.}/e - \alpha \times sd(Z_{i.})
\]</span> Where <span class="math inline">\(\alpha\)</span> is the quantile of the standard normal distribution at a given probability error (<span class="math inline">\(\alpha \approx 1.64\)</span> at 0.05). The method is implemented using the function <code><a href="../reference/Annicchiarico.html">Annicchiarico()</a></code>. The confidence index is estimated considering all environment, favorable environments (positive index) and unfavorable environments (negative index), as follows:</p>
<div class="sourceCode" id="cb7"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb7-1" title="1">ann5 =<span class="st"> </span><span class="kw"><a href="../reference/Annicchiarico.html">Annicchiarico</a></span>(dataset, ENV, GEN, REP, KW)</a>
<a class="sourceLine" id="cb7-2" title="2">ann1 =<span class="st"> </span><span class="kw"><a href="../reference/Annicchiarico.html">Annicchiarico</a></span>(dataset, ENV, GEN, REP, KW, <span class="dt">prob =</span> <span class="fl">0.01</span>)</a>
<a class="sourceLine" id="cb7-3" title="3"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(ann5)</a></code></pre></div>
<pre><code>## Variable KW 
## ---------------------------------------------------------------------------
## Environmental index
## ---------------------------------------------------------------------------
##  ENV Mean  index       class
##   A1  199  26.50   favorable
##   A2  168  -4.50 unfavorable
##   A3  147 -26.13 unfavorable
##   A4  177   4.13   favorable
## ---------------------------------------------------------------------------
## Analysis for all environments
## ---------------------------------------------------------------------------
##  Genotype Mean Mean_rp Sd_rp   Wi rank
##        H1  184   106.5  4.15 99.7    1
##       H10  164    94.2  8.80 79.7    7
##       H11  167    96.7  2.21 93.1    3
##       H12  157    91.3  9.92 75.0   11
##       H13  180   104.6 16.35 77.7    9
##        H2  187   108.6 15.64 82.9    5
##        H3  169    98.0 11.98 78.3    8
##        H4  184   106.5  8.77 92.0    4
##        H5  184   106.7  6.72 95.6    2
##        H6  188   108.0 16.74 80.5    6
##        H7  171    99.3 13.50 77.1   10
##        H8  160    92.1 17.29 63.7   12
##        H9  153    87.4 15.96 61.2   13
## ---------------------------------------------------------------------------
## Analysis for favorable environments
## ---------------------------------------------------------------------------
##  Genotype Mean Mean_rp Sd_rp   Wi rank
##        H1  195   103.7  2.93 98.9    1
##       H10  188    99.8  4.74 92.0    5
##       H11  182    97.0  3.69 90.9    6
##       H12  175    93.2  3.81 86.9    9
##       H13  184    97.2 17.58 68.3   13
##        H2  184    97.7  6.38 87.2    8
##        H3  174    92.0 10.50 74.7   12
##        H4  198   105.5  6.03 95.5    2
##        H5  194   103.2  9.34 87.9    7
##        H6  200   105.6 15.10 80.7   10
##        H7  192   102.9 16.78 75.3   11
##        H8  193   102.5  5.92 92.8    4
##        H9  188    99.8  3.69 93.7    3
## ---------------------------------------------------------------------------
## Analysis for unfavorable environments
## ---------------------------------------------------------------------------
##  Genotype Mean Mean_rp  Sd_rp    Wi rank
##        H1  173   109.3  3.477 103.6    2
##       H10  140    88.5  9.058  73.6    8
##       H11  152    96.5  0.909  95.0    4
##       H12  140    89.5 16.347  62.6   11
##       H13  175   112.0 16.491  84.9    5
##        H2  190   119.6 14.666  95.4    3
##        H3  165   104.0 13.217  82.3    7
##        H4  170   107.5 13.803  84.8    6
##        H5  174   110.2  0.584 109.2    1
##        H6  176   110.5 24.253  70.6   10
##        H7  150    95.7 14.602  71.7    9
##        H8  127    81.7 20.697  47.7   13
##        H9  117    75.1 11.829  55.6   12</code></pre>
</div>
<div id="superiority-index" class="section level1">
<h1 class="hasAnchor">
<a href="#superiority-index" class="anchor"></a>Superiority index</h1>
<p>The function <code><a href="../reference/superiority.html">superiority()</a></code> implements the nonparametric method proposed by <span class="citation">Lin and Binns (<a href="#ref-Lin1988">1988</a>)</span>, which considers that a measure of cultivar general superiority for cultivar x location data is defined as the distance mean square between the cultivar’s response and the maximum response averaged over all locations, according to the following model.</p>
<p><span class="math display">\[
P_i = \sum\limits_{j = 1}^n{(y_{ij} - y_{.j})^2/(2n)}
\]</span> where <em>n</em> is the number of environments</p>
<p>Similar then the genotypic confidence index, the superiority index is calculated by all environments, favorable, and unfavorable environments.</p>
<div class="sourceCode" id="cb9"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb9-1" title="1">super =<span class="st"> </span><span class="kw"><a href="../reference/superiority.html">superiority</a></span>(dataset, ENV, GEN, REP, KW)</a>
<a class="sourceLine" id="cb9-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(super)</a></code></pre></div>
<pre><code>## Variable KW 
## ---------------------------------------------------------------------------
## Superiority index considering all, favorable and unfavorable environments
## ---------------------------------------------------------------------------
##  Genotypes Pi_all Or_a Pi_favorable Or_f Pi_unfavorable Or_u
##         H1    332    1          276    2            389    3
##        H10   1147   10          494    7           1801   10
##        H11    918    8          655   10           1181    8
##        H12   1566   11          939   12           2194   11
##        H13    685    6          749   11            620    6
##         H2    337    2          561    8            113    1
##         H3    824    7          999   13            649    7
##         H4    362    3          245    1            478    4
##         H5    387    4          402    5            371    2
##         H6    404    5          309    3            499    5
##         H7   1105    9          633    9           1577    9
##         H8   1789   12          370    4           3207   12
##         H9   2073   13          434    6           3711   13
## ---------------------------------------------------------------------------</code></pre>
</div>
<div id="environmental-stratification" class="section level1">
<h1 class="hasAnchor">
<a href="#environmental-stratification" class="anchor"></a>Environmental stratification</h1>
<p>A method that combines stability analysis and environmental stratification using factor analysis was proposed by <span class="citation">Murakami and Cruz (<a href="#ref-murakami2004">2004</a>)</span>. This method is implemented with the function <code><a href="../reference/ge_factanal.html">ge_factanal()</a></code>, as follows:</p>
<div class="sourceCode" id="cb11"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb11-1" title="1">fact =<span class="st"> </span><span class="kw"><a href="../reference/ge_factanal.html">ge_factanal</a></span>(dataset, ENV, GEN, REP, KW, <span class="dt">mineval =</span> <span class="fl">0.9</span>)</a>
<a class="sourceLine" id="cb11-2" title="2"><span class="kw"><a href="https://www.rdocumentation.org/packages/graphics/topics/plot">plot</a></span>(fact<span class="op">$</span>KW)</a></code></pre></div>
<p><img src="vignettes_stability_files/figure-html/unnamed-chunk-6-1.png" width="480"></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><a class="sourceLine" id="cb12-1" title="1"><span class="kw"><a href="https://www.rdocumentation.org/packages/base/topics/summary">summary</a></span>(fact)</a></code></pre></div>
<pre><code>## Variable KW 
## ------------------------------------------------------------------------------------
## Correlation matrix among environments
## ------------------------------------------------------------------------------------
##         A1      A2      A3      A4
## A1  1.0000  0.4846  0.1126 -0.4588
## A2  0.4846  1.0000  0.2937 -0.2033
## A3  0.1126  0.2937  1.0000 -0.1121
## A4 -0.4588 -0.2033 -0.1121  1.0000
## ------------------------------------------------------------------------------------
## Eigenvalues and explained variance
## ------------------------------------------------------------------------------------
##  PCA Eigenvalues Variance Cumul_var
##  PC1      1.8766    46.92     46.92
##  PC2      0.9882    24.71     71.62
##  PC3      0.7315    18.29     89.91
##  PC4      0.4037    10.09    100.00
## ------------------------------------------------------------------------------------
## Initial loadings
## ------------------------------------------------------------------------------------
##  Env     PC1     PC2
##   A1 -0.8204  0.2949
##   A2 -0.7552 -0.2553
##   A3 -0.4429 -0.7923
##   A4  0.6612 -0.4565
## ------------------------------------------------------------------------------------
## Loadings after varimax rotation and commonalities
## ------------------------------------------------------------------------------------
##  Env      FA1     FA2 Communality Uniquenesses
##   A1 -0.85080 -0.1901      0.7600       0.2400
##   A2 -0.50119 -0.6200      0.6356       0.3644
##   A3  0.05004 -0.9063      0.8238       0.1762
##   A4  0.80279 -0.0316      0.6455       0.3545
## ------------------------------------------------------------------------------------
## Environmental stratification based on factor analysis
## ------------------------------------------------------------------------------------
##  Env Factor  Mean   Min   Max     CV
##   A1    FA1 199.4 180.5 231.9  7.073
##   A4    FA1 177.1 149.7 203.2  9.428
##   A2    FA2 168.4 112.3 218.9 21.046
##   A3    FA2 146.8 120.6 181.6 11.284
## ------------------------------------------------------------------------------------
## Mean = mean; Min = minimum; Max = maximum; CV = coefficient of variation (%)
## The summary statistics are based on the men values of  3 replicates
## ------------------------------------------------------------------------------------</code></pre>
</div>
<div id="references" class="section level1 unnumbered">
<h1 class="hasAnchor">
<a href="#references" class="anchor"></a>References</h1>
<div id="refs" class="references">
<div id="ref-Annicchiarico1992">
<p>Annicchiarico, P. 1992. “Cultivar adaptation and recommendation from alfalfa trials in Northern Italy.” <em>Journal of Genetics and Breeding</em> 46: 269–78.</p>
</div>
<div id="ref-Eberhart1966">
<p>Eberhart, S. A., and W. A. Russell. 1966. “Stability parameters for comparing Varieties.” <em>Crop Science</em> 6 (1): 36–40. <a href="https://doi.org/10.2135/cropsci1966.0011183X000600010011x">https://doi.org/10.2135/cropsci1966.0011183X000600010011x</a>.</p>
</div>
<div id="ref-Lin1988">
<p>Lin, C. S., and M. R. Binns. 1988. “A superiority measure of cultivar performance for cultivar x location data.” <em>Canadian Journal of Plant Science</em> 68 (1): 193–98. <a href="https://doi.org/10.4141/cjps88-018">https://doi.org/10.4141/cjps88-018</a>.</p>
</div>
<div id="ref-murakami2004">
<p>Murakami, D.M., and C.D. Cruz. 2004. “Proposal of methodologies for environment stratification and analysis of genotype adaptability.” <em>Crop Breeding and Applied Biotechnology</em> 4 (1): 7–11. <a href="http://www.sbmp.org.br/cbab/siscbab/uploads/c8128f42-aefe-cdf5.pdf">http://www.sbmp.org.br/cbab/siscbab/uploads/c8128f42-aefe-cdf5.pdf</a>.</p>
</div>
</div>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="sidebar">
        <div id="tocnav">
      <h2 class="hasAnchor">
<a href="#tocnav" class="anchor"></a>Contents</h2>
      <ul class="nav nav-pills nav-stacked">
<li><a href="#getting-started">Getting started</a></li>
      <li><a href="#graphic-visualization-of-the-interaction">Graphic visualization of the interaction</a></li>
      <li><a href="#joint-regression-analysis">Joint regression analysis</a></li>
      <li><a href="#genotypic-confidence-index">Genotypic confidence index</a></li>
      <li><a href="#superiority-index">Superiority index</a></li>
      <li><a href="#environmental-stratification">Environmental stratification</a></li>
      <li><a href="#references">References</a></li>
      </ul>
</div>
      </div>

</div>


      <footer><div class="copyright">
  <p>Developed by <a href="https://www.researchgate.net/profile/Tiago_Olivoto2">Tiago Olivoto</a>.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.3.0.</p>
</div>
      </footer>
</div>

  

  </body>
</html>
