#' Plot an object of class ge_reg
#'
#' Plot the regression model generated by the function \code{ge_reg}.
#'
#'
#' @param x An object of class \code{ge_factanal}
#' @param theme The graphical theme of the plot. Default is `theme =
#' theme_waasb()`. Please, see `?WAASB::theme_waasb`. An own theme can be
#' applied using the arguments: `theme = theme(some stuff
#' here)`. For more details, please, see `?ggplot2::theme`
#' @param x.lim The range of x-axis. Default is \code{NULL} (maximum and
#' minimum values of the data set). New arguments can be inserted as
#' \code{x.lim = c(x.min, x.max)}.
#' @param x.breaks The breaks to be plotted in the x-axis. Default is
#' \code{authomatic breaks}. New arguments can be inserted as \code{x.breaks =
#' c(breaks)}
#' @param x.lab The label of x-axis. Each plot has a default value. New
#' arguments can be inserted as \code{x.lab = "my label"}.
#' @param y.lim The range of x-axis. Default is \code{NULL}. The same arguments
#' than \code{x.lim} can be used.
#' @param y.breaks The breaks to be plotted in the x-axis. Default is
#' \code{authomatic breaks}. The same arguments than \code{x.breaks} can be
#' used.
#' @param y.lab The label of y-axis. Each plot has a default value. New
#' arguments can be inserted as \code{y.lab = "my label"}.
#' @param leg.position The position of the legend.
#' @param size.tex.lab The size of the text in the axes text and labels.
#' Default is \code{12}.
#' @param ... Other arguments of the function.
#' @author Tiago Olivoto \email{tiagoolivoto@@gmail.com}
#' @seealso \code{\link{ge_factanal}}
#' @method plot ge_reg
#' @return An object of class \code{gg, ggplot}.
#' @export
#' @examples
#' library(metan)
#' model = ge_reg(data_ge2, ENV, GEN, REP, PH)
#' plot(model$PH)
#'
plot.ge_reg <- function(x, theme = theme_waasb(), x.lim = NULL, x.breaks = waiver(),
                       x.lab = NULL, y.lim = NULL, y.breaks = waiver(), y.lab = NULL,
                       leg.position = "right", size.tex.lab = 12, ...){
  if (!class(x) == "ge_reg") {
    stop("The object 'x' is not of class 'ge_reg'")
  }
  if (is.null(y.lab) == FALSE) {
    y.lab <- y.lab
  } else {
    y.lab <- paste("Response variable")
  }
  if (is.null(x.lab) == FALSE) {
    x.lab <- x.lab
  } else {
    x.lab <- paste("Environmental index")
  }
  p = ggplot2::ggplot(x$data, aes(x = IndAmb, y = mean))+
    ggplot2::geom_point(aes(colour = GEN), size = 1.5)+
    geom_smooth(aes(colour = GEN), method = "lm", se = FALSE)+
    ggplot2::theme_bw()+
    ggplot2::labs(x = x.lab, y = y.lab)+
    theme %+replace% theme(axis.text = element_text(size = size.tex.lab, colour = "black"),
                           axis.title = element_text(size = size.tex.lab, colour = "black"),
                           axis.ticks = element_line(color = "black"),
                           axis.ticks.length = unit(.2, "cm"),
                           legend.position = leg.position)
  return(p)
}
