#' Summarize an object generated by the function \code{path_coeff()}
#'
#' Summarize an object generated by the function 'path_coeff()'. By default,
#' the results are shown in the R console. The results can also be exported to
#' the directory.
#'
#'
#' @param object An object of class \code{path_coeff} or \code{brute_path} or
#' \code{group_path}
#' @param model If \code{object} if of class \code{brute_path}, then
#' \code{model} is the number of the fitted model that will be summarized.
#' @param export A logical argument. If \code{TRUE}, a *.txt file is exported
#' to the working directory
#' @param file.name The name of the file if \code{export = TRUE}
#' @param digits The significant digits to be shown.
#' @param ... Other arguments of the function
#' @author Tiago Olivoto \email{tiagoolivoto@@gmail.com}
#' @method summary path_coeff
#' @export
#' @examples
#'
#' \dontrun{
#' library(metan)
#'
#' # KW as dependent trait and all others as predictors
#' pcoeff = path_coeff(data_ge2, resp = KW)
#' summary(pcoeff)
#'
#' # Call the algorithm for selecting a set of predictors
#' # with minimal multicollinearity (no VIF larger than 5)
#' pcoeff2 = path_coeff(data_ge2,
#'                      resp = KW,
#'                      brutstep = TRUE,
#'                      maxvif = 5)
#' summary(pcoeff2)
#' }
#'
summary.path_coeff = function(object,
                              model = NULL,
                              export = FALSE,
                              file.name = "path_coeff",
                              digits = 4,
                              ...){
  if(export  ==  TRUE){
    sink(paste0(file.name,".txt"))
    options(max.print = 99999999, width = 100)
    options(digits = digits)
  if(class(object) == "path_coeff"){
      data = object
      if (!is.null(model) && class(data) == "path_coeff"){
        stop("You cannot inform a model if the data to be summarized is of class 'path_coeff'.")
      }
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Correlation matrix between the predictor traits\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(data$Corr.x)
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Vector of correlations between dependent and each predictor\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(t(data$Corr.y))
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Multicollinearity diagnosis and goodness-of-fit\n")
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Condition number: ", round(data$CN,4), "\n")
      cat("Determinant:      ", round(data$Det,8), "\n")
      cat("R-square:         ", round(data$R2,4), "\n")
      cat("Residual:         ", round(data$Residual,4), "\n")
      cat("Response:         ", paste(data$Response)[[2]], "\n")
      cat("Predictors:       ", paste(data$Predictors), "\n")
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Variance inflation factors\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(data$VIF)
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Eigenvalues and eigenvectors\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(data$Eigen)
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Variables with the largest weight in the eigenvalue of smallest magnitude\n")
      cat("----------------------------------------------------------------------------------------------\n")
      cat(data$weightvar, "\n")
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Direct (diagonal) and indirect (off-diagonal) effects\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(data$Coefficients)
      cat("----------------------------------------------------------------------------------------------\n")
    }
  if(class(object) == "brute_path"){
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Summary of fitted models\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(object$Summary)
      cat("----------------------------------------------------------------------------------------------\n")

      cat("To summary a specific model, use the argument 'model = x' where x is the desired model.\n\n\n")
      cat("\n")

      if (!is.null(model)){
        data = object[["Models"]][[model]]
        cat("\n\n----------------------------------------------------------------------------------------------\n")
        cat("Correlation matrix between the predictor traits\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Corr.x)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Vector of correlations between dependent and each predictor\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(t(data$Corr.y))
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Multicollinearity diagnosis and goodness-of-fit\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Condition number: ", round(data$CN,4), "\n")
        cat("Determinant:      ", round(data$Det,8), "\n")
        cat("R-square:         ", round(data$R2,4), "\n")
        cat("Residual:         ", round(data$Residual,4), "\n")
        cat("Response:         ", paste(data$Response)[[2]], "\n")
        cat("Predictors:       ", paste(data$Predictors), "\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Variance inflation factors\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$VIF)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Eigenvalues and eigenvectors\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Eigen)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Variables with the largest weight in the eigenvalue of smallest magnitude\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat(data$weightvar, "\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Direct (diagonal) and indirect (off-diagonal) effects\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Coefficients)
        cat("----------------------------------------------------------------------------------------------\n")

      }
    }
  if(any(class(object) == "group_path")){
    for (k in 1:length(object)){
      data = object[[k]]
      nam  = names(object[k])
      if (!is.null(model) && class(data) == "path_coeff"){
        stop("You cannot inform a model if the data to be summarized is of class 'path_coeff'.")
      }
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Level:", names(object)[[k]], "\n")
      if(class(data) == "path_coeff"){
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Correlation matrix between the predictor traits\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Corr.x)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Vector of correlations between dependent and each predictor\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(t(data$Corr.y))
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Multicollinearity diagnosis and goodness-of-fit\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Condition number: ", round(data$CN,4), "\n")
        cat("Determinant:      ", round(data$Det,8), "\n")
        cat("R-square:         ", round(data$R2,4), "\n")
        cat("Residual:         ", round(data$Residual,4), "\n")
        cat("Response:         ", paste(data$Response)[[2]], "\n")
        cat("Predictors:       ", paste(data$Predictors), "\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Variance inflation factors\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$VIF)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Eigenvalues and eigenvectors\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Eigen)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Variables with the largest weight in the eigenvalue of smallest magnitude\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat(data$weightvar, "\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Direct (diagonal) and indirect (off-diagonal) effects\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Coefficients)
        cat("----------------------------------------------------------------------------------------------\n\n\n")
      }
      if(class(data) == "brute_path"){
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Summary of fitted models\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Summary)
        cat("----------------------------------------------------------------------------------------------\n")

        cat("To summary a specific model, use the argument 'model = x' where x is the desired model.\n\n\n")
        cat("\n")

        if (!is.null(model)){
          tmp = data[["Models"]][[model]]
          cat("\n")
          cat("\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Correlation matrix between the predictor traits\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(tmp$Corr.x)
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Vector of correlations between dependent and each predictor\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(t(tmp$Corr.y))
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Multicollinearity diagnosis and goodness-of-fit\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Condition number: ", round(tmp$CN,4), "\n")
          cat("Determinant:      ", round(tmp$Det,8), "\n")
          cat("R-square:         ", round(tmp$R2,4), "\n")
          cat("Residual:         ", round(tmp$Residual,4), "\n")
          cat("Response:         ", paste(tmp$Response)[[2]], "\n")
          cat("Predictors:       ", paste(tmp$Predictors), "\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Variance inflation factors\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(tmp$VIF)
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Eigenvalues and eigenvectors\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(tmp$Eigen)
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Variables with the largest weight in the eigenvalue of smallest magnitude\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat(tmp$weightvar, "\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Direct (diagonal) and indirect (off-diagonal) effects\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(tmp$Coefficients)
          cat("----------------------------------------------------------------------------------------------\n\n\n")

        }
      }

    }
  }
    sink()
  }

  if(export  ==  FALSE){
    options(digits = digits)
    if(class(object) == "path_coeff"){
      data = object
      if (!is.null(model) && class(data) == "path_coeff"){
        stop("You cannot inform a model if the data to be summarized is of class 'path_coeff'.")
      }
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Correlation matrix between the predictor traits\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(data$Corr.x)
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Vector of correlations between dependent and each predictor\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(t(data$Corr.y))
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Multicollinearity diagnosis and goodness-of-fit\n")
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Condition number: ", round(data$CN,4), "\n")
      cat("Determinant:      ", round(data$Det,8), "\n")
      cat("R-square:         ", round(data$R2,4), "\n")
      cat("Residual:         ", round(data$Residual,4), "\n")
      cat("Response:         ", paste(data$Response)[[2]], "\n")
      cat("Predictors:       ", paste(data$Predictors), "\n")
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Variance inflation factors\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(data$VIF)
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Eigenvalues and eigenvectors\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(data$Eigen)
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Variables with the largest weight in the eigenvalue of smallest magnitude\n")
      cat("----------------------------------------------------------------------------------------------\n")
      cat(data$weightvar, "\n")
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Direct (diagonal) and indirect (off-diagonal) effects\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(data$Coefficients)
      cat("----------------------------------------------------------------------------------------------\n")
    }
    if(class(object) == "brute_path"){
      cat("----------------------------------------------------------------------------------------------\n")
      cat("Summary of fitted models\n")
      cat("----------------------------------------------------------------------------------------------\n")
      print(object$Summary)
      cat("----------------------------------------------------------------------------------------------\n")

      cat("To summary a specific model, use the argument 'model = x' where x is the desired model.\n\n\n")
      cat("\n")

      if (!is.null(model)){
        data = object[["Models"]][[model]]
        cat("\n\n----------------------------------------------------------------------------------------------\n")
        cat("Correlation matrix between the predictor traits\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Corr.x)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Vector of correlations between dependent and each predictor\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(t(data$Corr.y))
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Multicollinearity diagnosis and goodness-of-fit\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Condition number: ", round(data$CN,4), "\n")
        cat("Determinant:      ", round(data$Det,8), "\n")
        cat("R-square:         ", round(data$R2,4), "\n")
        cat("Residual:         ", round(data$Residual,4), "\n")
        cat("Response:         ", paste(data$Response)[[2]], "\n")
        cat("Predictors:       ", paste(data$Predictors), "\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Variance inflation factors\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$VIF)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Eigenvalues and eigenvectors\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Eigen)
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Variables with the largest weight in the eigenvalue of smallest magnitude\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat(data$weightvar, "\n")
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Direct (diagonal) and indirect (off-diagonal) effects\n")
        cat("----------------------------------------------------------------------------------------------\n")
        print(data$Coefficients)
        cat("----------------------------------------------------------------------------------------------\n")

      }
    }
    if(any(class(object) == "group_path")){
      for (k in 1:length(object)){
        data = object[[k]]
        nam  = names(object[k])
        if (!is.null(model) && class(data) == "path_coeff"){
          stop("You cannot inform a model if the data to be summarized is of class 'path_coeff'.")
        }
        cat("----------------------------------------------------------------------------------------------\n")
        cat("Level:", names(object)[[k]], "\n")
        if(class(data) == "path_coeff"){
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Correlation matrix between the predictor traits\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(data$Corr.x)
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Vector of correlations between dependent and each predictor\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(t(data$Corr.y))
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Multicollinearity diagnosis and goodness-of-fit\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Condition number: ", round(data$CN,4), "\n")
          cat("Determinant:      ", round(data$Det,8), "\n")
          cat("R-square:         ", round(data$R2,4), "\n")
          cat("Residual:         ", round(data$Residual,4), "\n")
          cat("Response:         ", paste(data$Response)[[2]], "\n")
          cat("Predictors:       ", paste(data$Predictors), "\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Variance inflation factors\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(data$VIF)
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Eigenvalues and eigenvectors\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(data$Eigen)
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Variables with the largest weight in the eigenvalue of smallest magnitude\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat(data$weightvar, "\n")
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Direct (diagonal) and indirect (off-diagonal) effects\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(data$Coefficients)
          cat("----------------------------------------------------------------------------------------------\n\n\n")
        }
        if(class(data) == "brute_path"){
          cat("----------------------------------------------------------------------------------------------\n")
          cat("Summary of fitted models\n")
          cat("----------------------------------------------------------------------------------------------\n")
          print(data$Summary)
          cat("----------------------------------------------------------------------------------------------\n")

          cat("To summary a specific model, use the argument 'model = x' where x is the desired model.\n\n\n")
          cat("\n")

          if (!is.null(model)){
            tmp = data[["Models"]][[model]]
            cat("\n")
            cat("\n")
            cat("----------------------------------------------------------------------------------------------\n")
            cat("Correlation matrix between the predictor traits\n")
            cat("----------------------------------------------------------------------------------------------\n")
            print(tmp$Corr.x)
            cat("----------------------------------------------------------------------------------------------\n")
            cat("Vector of correlations between dependent and each predictor\n")
            cat("----------------------------------------------------------------------------------------------\n")
            print(t(tmp$Corr.y))
            cat("----------------------------------------------------------------------------------------------\n")
            cat("Multicollinearity diagnosis and goodness-of-fit\n")
            cat("----------------------------------------------------------------------------------------------\n")
            cat("Condition number: ", round(tmp$CN,4), "\n")
            cat("Determinant:      ", round(tmp$Det,8), "\n")
            cat("R-square:         ", round(tmp$R2,4), "\n")
            cat("Residual:         ", round(tmp$Residual,4), "\n")
            cat("Response:         ", paste(tmp$Response)[[2]], "\n")
            cat("Predictors:       ", paste(tmp$Predictors), "\n")
            cat("----------------------------------------------------------------------------------------------\n")
            cat("Variance inflation factors\n")
            cat("----------------------------------------------------------------------------------------------\n")
            print(tmp$VIF)
            cat("----------------------------------------------------------------------------------------------\n")
            cat("Eigenvalues and eigenvectors\n")
            cat("----------------------------------------------------------------------------------------------\n")
            print(tmp$Eigen)
            cat("----------------------------------------------------------------------------------------------\n")
            cat("Variables with the largest weight in the eigenvalue of smallest magnitude\n")
            cat("----------------------------------------------------------------------------------------------\n")
            cat(tmp$weightvar, "\n")
            cat("----------------------------------------------------------------------------------------------\n")
            cat("Direct (diagonal) and indirect (off-diagonal) effects\n")
            cat("----------------------------------------------------------------------------------------------\n")
            print(tmp$Coefficients)
            cat("----------------------------------------------------------------------------------------------\n\n\n")

          }
        }
      }
    }
  }
}
