summary.can_cor <- function(object, export = FALSE, file.name = NULL, digits = 4, ...) {
  if (!class(object) == "can_cor") {
    stop("The object must be of class 'can_cor'")
  }
  if (export == TRUE) {
    if (is.null(file.name) == T) {
      file.name <- "Canonical summary"
    } else {
      file.name <- file.name
    }
    sink(paste0(file.name, ".txt"))
    options(max.print = 99999999, width = 110)
    cat("---------------------------------------------------------------------------\n")
    cat("Matrix (correlation/covariance) between variables of first group (FG)\n")
    cat("---------------------------------------------------------------------------\n")
    print(object$MFG)
    cat("\n---------------------------------------------------------------------------\n")
    cat("Collinearity diagnostic between first group\n")
    cat("---------------------------------------------------------------------------\n")
    colindiag(object$MFG, n = nrow(object$Score_FG))
    cat("\n---------------------------------------------------------------------------\n")
    cat("Matrix (correlation/covariance) between variables of second group (SG)\n")
    cat("---------------------------------------------------------------------------\n")
    print(object$MSG)
    cat("\n---------------------------------------------------------------------------\n")
    cat("Collinearity diagnostic between second group\n")
    cat("---------------------------------------------------------------------------\n")
    colindiag(object$MSG, n = nrow(object$Score_SG))
    cat("\n---------------------------------------------------------------------------\n")
    cat("Matrix (correlation/covariance) between FG and SG)\n")
    cat("---------------------------------------------------------------------------\n")
    print(object$MFG_SG)
    cat("\n---------------------------------------------------------------------------\n")
    cat("Correlation of the canonical pairs and hipotesis testing \n")
    cat("---------------------------------------------------------------------------\n")
    print(object$SigTest)
    cat("\n---------------------------------------------------------------------------\n")
    cat("Canonical coefficients of the first group \n")
    cat("---------------------------------------------------------------------------\n")
    print(object$Coef_FG)
    cat("\n---------------------------------------------------------------------------\n")
    cat("Canonical coefficients of the second group \n")
    cat("---------------------------------------------------------------------------\n")
    print(object$Coef_SG)
    cat("\n---------------------------------------------------------------------------\n")
    cat("Canonical loads of the first group \n")
    cat("---------------------------------------------------------------------------\n")
    print(object$Loads_FG)
    cat("\n---------------------------------------------------------------------------\n")
    cat("Canonical loads of the second group \n")
    cat("---------------------------------------------------------------------------\n")
    print(object$Loads_SG)
    cat("\n-------------------------- End of data ------------------------------------\n\n\n\n")
    sink()
  } else {
    options(digits = digits)
      cat("---------------------------------------------------------------------------\n")
      cat("Matrix (correlation/covariance) between variables of first group (FG)\n")
      cat("---------------------------------------------------------------------------\n")
      print(object$MFG)
      cat("\n---------------------------------------------------------------------------\n")
      cat("Collinearity diagnostic between first group\n")
      cat("---------------------------------------------------------------------------\n")
      colindiag(object$MFG, n = nrow(object$Score_FG))
      cat("\n---------------------------------------------------------------------------\n")
      cat("Matrix (correlation/covariance) between variables of second group (SG)\n")
      cat("---------------------------------------------------------------------------\n")
      print(object$MSG)
      cat("\n---------------------------------------------------------------------------\n")
      cat("Collinearity diagnostic between second group\n")
      cat("---------------------------------------------------------------------------\n")
      colindiag(object$MSG, n = nrow(object$Score_SG))
      cat("\n---------------------------------------------------------------------------\n")
      cat("Matrix (correlation/covariance) between FG and SG)\n")
      cat("---------------------------------------------------------------------------\n")
      print(object$MFG_SG)
      cat("\n---------------------------------------------------------------------------\n")
      cat("Correlation of the canonical pairs and hipotesis testing \n")
      cat("---------------------------------------------------------------------------\n")
      print(object$SigTest)
      cat("\n---------------------------------------------------------------------------\n")
      cat("Canonical coefficients of the first group \n")
      cat("---------------------------------------------------------------------------\n")
      print(object$Coef_FG)
      cat("\n---------------------------------------------------------------------------\n")
      cat("Canonical coefficients of the second group \n")
      cat("---------------------------------------------------------------------------\n")
      print(object$Coef_SG)
      cat("\n---------------------------------------------------------------------------\n")
      cat("Canonical loads of the first group \n")
      cat("---------------------------------------------------------------------------\n")
      print(object$Loads_FG)
      cat("\n---------------------------------------------------------------------------\n")
      cat("Canonical loads of the second group \n")
      cat("---------------------------------------------------------------------------\n")
      print(object$Loads_SG)
      cat("\n-------------------------- End of data ------------------------------------\n\n\n\n")  }
}
